
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041c\u0438\u0445\u0430\u0438\u043b/AppData/Local/Microsoft/WinGet/Packages/Kitware.CMake_Microsoft.Winget.Source_8wekyb3d8bbwe/cmake-4.4.3-windows-x86_64/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
